// The recipe list: 40 dishes, Filipino, Chinese and Western.
//
// This is the single source of the starter recipes. db/seed.js loads it into
// PostgreSQL, and the client's demo mode (client/src/api/mockApi.js) reads the
// same file, so both always show the same list.
//
// Each ingredient is [name, quantity, unit, estimated cost in pesos]. The cost
// is for the whole quantity, not per unit.
//
// image is either a file in client/public/, e.g. 'recipes/chicken-adobo.jpg'
// for client/public/recipes/chicken-adobo.jpg, or a full https:// URL. Leave it
// as '' for no picture. A missing or broken image shows a placeholder instead.
//
// calories is a rough estimate per serving, used for the home screen's
// average. Adjust any of them freely.

const data = [
  // Filipino
  {
    name: 'Chicken Adobo', cuisine: 'Filipino', minutes: 45,
    image: 'recipes/chicken-adobo.jpg', calories: 450,
    ingredients: [
      ['Chicken thighs', 1, 'kg', 260],
      ['Soy sauce', 0.5, 'cup', 20],
      ['Cane vinegar', 0.5, 'cup', 15],
      ['Garlic', 1, 'head', 15],
      ['Bay leaves', 3, 'pc', 5],
      ['Whole peppercorns', 1, 'tsp', 5],
      ['Brown sugar', 1, 'tbsp', 3],
    ],
  },
  {
    name: 'Pork Sinigang', cuisine: 'Filipino', minutes: 60,
    image: 'recipes/pork-sinigang.jpg', calories: 400,
    ingredients: [
      ['Pork ribs', 1, 'kg', 340],
      ['Tamarind soup mix', 1, 'pack', 25],
      ['Kangkong', 1, 'bunch', 20],
      ['Radish', 1, 'pc', 30],
      ['String beans', 1, 'bunch', 25],
      ['Tomatoes', 2, 'pc', 20],
      ['Onion', 1, 'pc', 15],
      ['Long green chili', 2, 'pc', 5],
      ['Fish sauce', 2, 'tbsp', 5],
    ],
  },
  {
    name: 'Kare-Kare', cuisine: 'Filipino', minutes: 150,
    image: 'recipes/kare-kare.jpg', calories: 600,
    ingredients: [
      ['Oxtail', 1, 'kg', 550],
      ['Peanut butter', 0.5, 'cup', 60],
      ['Toasted rice flour', 3, 'tbsp', 15],
      ['Eggplant', 2, 'pc', 40],
      ['Pechay', 1, 'bunch', 25],
      ['String beans', 1, 'bunch', 25],
      ['Annatto powder', 1, 'tbsp', 10],
      ['Bagoong alamang', 0.5, 'cup', 60],
    ],
  },
  {
    name: 'Lumpiang Shanghai', cuisine: 'Filipino', minutes: 50,
    image: 'recipes/lumpiang-shanghai.jpg', calories: 380,
    ingredients: [
      ['Ground pork', 500, 'g', 170],
      ['Lumpia wrappers', 1, 'pack', 45],
      ['Carrot', 1, 'pc', 20],
      ['Onion', 1, 'pc', 15],
      ['Garlic', 4, 'clove', 8],
      ['Egg', 1, 'pc', 9],
      ['Cooking oil', 2, 'cup', 60],
    ],
  },
  {
    name: 'Pancit Canton', cuisine: 'Filipino', minutes: 35,
    image: 'recipes/pancit-canton.jpg', calories: 420,
    ingredients: [
      ['Canton noodles', 500, 'g', 70],
      ['Chicken breast', 250, 'g', 80],
      ['Shrimp', 200, 'g', 120],
      ['Cabbage', 0.5, 'head', 35],
      ['Carrot', 1, 'pc', 20],
      ['Snow peas', 100, 'g', 35],
      ['Soy sauce', 3, 'tbsp', 8],
      ['Oyster sauce', 2, 'tbsp', 12],
    ],
  },
  {
    name: 'Tinolang Manok', cuisine: 'Filipino', minutes: 50,
    image: 'recipes/tinolang-manok.jpg', calories: 300,
    ingredients: [
      ['Chicken', 1, 'kg', 240],
      ['Green papaya', 1, 'pc', 40],
      ['Chili leaves', 1, 'bunch', 15],
      ['Ginger', 50, 'g', 10],
      ['Onion', 1, 'pc', 15],
      ['Garlic', 3, 'clove', 6],
      ['Fish sauce', 2, 'tbsp', 5],
    ],
  },
  {
    name: 'Bicol Express', cuisine: 'Filipino', minutes: 45,
    image: 'recipes/bicol-express.jpg', calories: 550,
    ingredients: [
      ['Pork belly', 500, 'g', 190],
      ['Coconut milk', 2, 'can', 90],
      ['Shrimp paste', 2, 'tbsp', 15],
      ['Long green chili', 6, 'pc', 20],
      ['Siling labuyo', 5, 'pc', 10],
      ['Onion', 1, 'pc', 15],
      ['Garlic', 4, 'clove', 8],
    ],
  },
  {
    name: 'Beef Caldereta', cuisine: 'Filipino', minutes: 120,
    image: 'recipes/beef-caldereta.jpg', calories: 520,
    ingredients: [
      ['Beef chuck', 1, 'kg', 480],
      ['Tomato sauce', 250, 'g', 35],
      ['Liver spread', 1, 'can', 40],
      ['Potatoes', 2, 'pc', 40],
      ['Carrot', 1, 'pc', 20],
      ['Red bell pepper', 1, 'pc', 30],
      ['Cheese', 50, 'g', 30],
    ],
  },
  {
    name: 'Pork Menudo', cuisine: 'Filipino', minutes: 60,
    image: 'recipes/pork-menudo.jpg', calories: 450,
    ingredients: [
      ['Pork shoulder', 500, 'g', 180],
      ['Pork liver', 200, 'g', 50],
      ['Potatoes', 2, 'pc', 40],
      ['Carrot', 1, 'pc', 20],
      ['Tomato sauce', 250, 'g', 35],
      ['Raisins', 50, 'g', 25],
      ['Red bell pepper', 1, 'pc', 30],
    ],
  },
  {
    name: 'Chicken Afritada', cuisine: 'Filipino', minutes: 50,
    image: 'recipes/chicken-afritada.jpg', calories: 400,
    ingredients: [
      ['Chicken', 1, 'kg', 240],
      ['Tomato sauce', 250, 'g', 35],
      ['Potatoes', 2, 'pc', 40],
      ['Carrot', 1, 'pc', 20],
      ['Green bell pepper', 1, 'pc', 25],
      ['Green peas', 100, 'g', 30],
      ['Onion', 1, 'pc', 15],
    ],
  },
  {
    name: 'Laing', cuisine: 'Filipino', minutes: 60,
    image: 'recipes/laing.jpg', calories: 350,
    ingredients: [
      ['Dried taro leaves', 100, 'g', 60],
      ['Coconut milk', 2, 'can', 90],
      ['Coconut cream', 1, 'can', 50],
      ['Pork belly', 200, 'g', 75],
      ['Shrimp paste', 2, 'tbsp', 15],
      ['Siling labuyo', 5, 'pc', 10],
      ['Ginger', 50, 'g', 10],
    ],
  },
  {
    name: 'Pinakbet', cuisine: 'Filipino', minutes: 40,
    image: 'recipes/pinakbet.jpg', calories: 250,
    ingredients: [
      ['Squash', 250, 'g', 30],
      ['Eggplant', 2, 'pc', 40],
      ['Ampalaya', 1, 'pc', 35],
      ['Okra', 8, 'pc', 25],
      ['String beans', 1, 'bunch', 25],
      ['Tomatoes', 2, 'pc', 20],
      ['Pork belly', 200, 'g', 75],
      ['Shrimp paste', 3, 'tbsp', 20],
    ],
  },
  {
    name: 'Bistek Tagalog', cuisine: 'Filipino', minutes: 40,
    image: 'recipes/bistek-tagalog.jpg', calories: 420,
    ingredients: [
      ['Beef sirloin', 500, 'g', 280],
      ['Calamansi', 10, 'pc', 25],
      ['Soy sauce', 0.5, 'cup', 20],
      ['Onions', 2, 'pc', 30],
      ['Garlic', 4, 'clove', 8],
      ['Ground black pepper', 1, 'tsp', 5],
    ],
  },
  {
    name: 'Arroz Caldo', cuisine: 'Filipino', minutes: 60,
    image: 'recipes/arroz-caldo.jpg', calories: 350,
    ingredients: [
      ['Chicken', 500, 'g', 130],
      ['Glutinous rice', 1, 'cup', 40],
      ['Ginger', 50, 'g', 10],
      ['Garlic', 1, 'head', 15],
      ['Fish sauce', 2, 'tbsp', 5],
      ['Kasubha', 1, 'tbsp', 10],
      ['Green onions', 1, 'bunch', 10],
      ['Eggs', 4, 'pc', 36],
    ],
  },

  // Chinese
  {
    name: 'Sweet and Sour Pork', cuisine: 'Chinese', minutes: 45,
    image: 'recipes/sweet-and-sour-pork.jpg', calories: 500,
    ingredients: [
      ['Pork shoulder', 500, 'g', 180],
      ['Pineapple chunks', 1, 'can', 55],
      ['Red bell pepper', 1, 'pc', 30],
      ['Green bell pepper', 1, 'pc', 25],
      ['Onion', 1, 'pc', 15],
      ['Cornstarch', 0.5, 'cup', 15],
      ['Ketchup', 0.25, 'cup', 15],
      ['Rice vinegar', 3, 'tbsp', 10],
    ],
  },
  {
    name: 'Kung Pao Chicken', cuisine: 'Chinese', minutes: 30,
    image: 'recipes/kung-pao-chicken.jpg', calories: 430,
    ingredients: [
      ['Chicken thighs', 500, 'g', 140],
      ['Roasted peanuts', 100, 'g', 30],
      ['Dried red chilies', 10, 'pc', 20],
      ['Sichuan peppercorns', 1, 'tsp', 20],
      ['Green onions', 1, 'bunch', 10],
      ['Soy sauce', 2, 'tbsp', 5],
      ['Black vinegar', 1, 'tbsp', 10],
      ['Sugar', 1, 'tbsp', 3],
    ],
  },
  {
    name: 'Mapo Tofu', cuisine: 'Chinese', minutes: 30,
    image: 'recipes/mapo-tofu.jpg', calories: 380,
    ingredients: [
      ['Firm tofu', 500, 'g', 60],
      ['Ground pork', 200, 'g', 70],
      ['Doubanjiang', 2, 'tbsp', 30],
      ['Sichuan peppercorns', 1, 'tsp', 20],
      ['Garlic', 3, 'clove', 6],
      ['Ginger', 30, 'g', 6],
      ['Green onions', 1, 'bunch', 10],
      ['Cornstarch', 1, 'tbsp', 3],
    ],
  },
  {
    name: 'Beef with Broccoli', cuisine: 'Chinese', minutes: 30,
    image: 'recipes/beef-with-broccoli.jpg', calories: 400,
    ingredients: [
      ['Beef flank', 500, 'g', 260],
      ['Broccoli', 1, 'head', 70],
      ['Oyster sauce', 3, 'tbsp', 18],
      ['Soy sauce', 2, 'tbsp', 5],
      ['Garlic', 3, 'clove', 6],
      ['Ginger', 30, 'g', 6],
      ['Cornstarch', 1, 'tbsp', 3],
    ],
  },
  {
    name: 'Yangzhou Fried Rice', cuisine: 'Chinese', minutes: 25,
    image: 'recipes/yangzhou-fried-rice.jpg', calories: 520,
    ingredients: [
      ['Cooked rice', 4, 'cup', 40],
      ['Char siu', 150, 'g', 90],
      ['Shrimp', 150, 'g', 90],
      ['Eggs', 3, 'pc', 27],
      ['Green peas', 100, 'g', 30],
      ['Green onions', 1, 'bunch', 10],
      ['Soy sauce', 1, 'tbsp', 3],
    ],
  },
  {
    name: 'Steamed Fish with Ginger and Scallion', cuisine: 'Chinese', minutes: 30,
    image: 'recipes/steamed-fish-with-ginger-and-scallion.jpg', calories: 280,
    ingredients: [
      ['Whole lapu-lapu', 700, 'g', 350],
      ['Ginger', 50, 'g', 10],
      ['Green onions', 1, 'bunch', 10],
      ['Light soy sauce', 3, 'tbsp', 8],
      ['Sesame oil', 1, 'tbsp', 10],
      ['Cooking oil', 3, 'tbsp', 8],
    ],
  },
  {
    name: 'Hot and Sour Soup', cuisine: 'Chinese', minutes: 30,
    image: 'recipes/hot-and-sour-soup.jpg', calories: 180,
    ingredients: [
      ['Firm tofu', 250, 'g', 30],
      ['Shiitake mushrooms', 100, 'g', 60],
      ['Bamboo shoots', 1, 'can', 45],
      ['Eggs', 2, 'pc', 18],
      ['Chicken stock', 4, 'cup', 40],
      ['Rice vinegar', 3, 'tbsp', 10],
      ['White pepper', 1, 'tsp', 8],
      ['Cornstarch', 2, 'tbsp', 5],
    ],
  },
  {
    name: 'Char Siu', cuisine: 'Chinese', minutes: 180,
    image: 'recipes/char-siu.jpg', calories: 450,
    ingredients: [
      ['Pork shoulder', 1, 'kg', 360],
      ['Hoisin sauce', 3, 'tbsp', 30],
      ['Honey', 3, 'tbsp', 35],
      ['Soy sauce', 2, 'tbsp', 5],
      ['Chinese five-spice', 1, 'tsp', 10],
      ['Shaoxing wine', 2, 'tbsp', 25],
      ['Garlic', 4, 'clove', 8],
    ],
  },
  {
    name: 'Pork and Chive Dumplings', cuisine: 'Chinese', minutes: 75,
    image: 'recipes/pork-and-chive-dumplings.jpg', calories: 400,
    ingredients: [
      ['Ground pork', 500, 'g', 170],
      ['Dumpling wrappers', 1, 'pack', 60],
      ['Chinese chives', 1, 'bunch', 25],
      ['Ginger', 30, 'g', 6],
      ['Soy sauce', 2, 'tbsp', 5],
      ['Sesame oil', 1, 'tbsp', 10],
    ],
  },
  {
    name: 'Chicken Chow Mein', cuisine: 'Chinese', minutes: 30,
    image: 'recipes/chicken-chow-mein.jpg', calories: 450,
    ingredients: [
      ['Egg noodles', 400, 'g', 60],
      ['Chicken breast', 250, 'g', 80],
      ['Cabbage', 0.5, 'head', 35],
      ['Carrot', 1, 'pc', 20],
      ['Bean sprouts', 200, 'g', 20],
      ['Oyster sauce', 2, 'tbsp', 12],
      ['Soy sauce', 2, 'tbsp', 5],
    ],
  },
  {
    name: 'Egg Drop Soup', cuisine: 'Chinese', minutes: 15,
    image: 'recipes/egg-drop-soup.jpg', calories: 120,
    ingredients: [
      ['Chicken stock', 4, 'cup', 40],
      ['Eggs', 3, 'pc', 27],
      ['Cornstarch', 2, 'tbsp', 5],
      ['Green onions', 1, 'bunch', 10],
      ['Sesame oil', 1, 'tsp', 5],
      ['White pepper', 0.5, 'tsp', 4],
    ],
  },
  {
    name: 'Cashew Chicken', cuisine: 'Chinese', minutes: 30,
    image: 'recipes/cashew-chicken.jpg', calories: 450,
    ingredients: [
      ['Chicken breast', 500, 'g', 160],
      ['Cashew nuts', 100, 'g', 70],
      ['Red bell pepper', 1, 'pc', 30],
      ['Onion', 1, 'pc', 15],
      ['Hoisin sauce', 2, 'tbsp', 20],
      ['Soy sauce', 2, 'tbsp', 5],
      ['Garlic', 3, 'clove', 6],
    ],
  },
  {
    name: 'Red Braised Pork Belly', cuisine: 'Chinese', minutes: 90,
    image: 'recipes/red-braised-pork-belly.jpg', calories: 600,
    ingredients: [
      ['Pork belly', 1, 'kg', 380],
      ['Rock sugar', 50, 'g', 15],
      ['Shaoxing wine', 3, 'tbsp', 35],
      ['Dark soy sauce', 2, 'tbsp', 10],
      ['Light soy sauce', 2, 'tbsp', 5],
      ['Star anise', 2, 'pc', 5],
      ['Ginger', 50, 'g', 10],
    ],
  },

  // Western
  {
    name: 'Spaghetti Bolognese', cuisine: 'Western', minutes: 60,
    image: 'recipes/spaghetti-bolognese.jpg', calories: 600,
    ingredients: [
      ['Spaghetti', 500, 'g', 90],
      ['Ground beef', 500, 'g', 220],
      ['Crushed tomatoes', 1, 'can', 70],
      ['Onion', 1, 'pc', 15],
      ['Carrot', 1, 'pc', 20],
      ['Celery', 2, 'stalk', 20],
      ['Garlic', 3, 'clove', 6],
      ['Parmesan', 50, 'g', 90],
    ],
  },
  {
    name: 'Spaghetti Carbonara', cuisine: 'Western', minutes: 25,
    image: 'recipes/spaghetti-carbonara.jpg', calories: 650,
    ingredients: [
      ['Spaghetti', 500, 'g', 90],
      ['Bacon', 200, 'g', 130],
      ['Eggs', 3, 'pc', 27],
      ['Parmesan', 80, 'g', 140],
      ['Ground black pepper', 1, 'tsp', 5],
      ['Garlic', 2, 'clove', 4],
    ],
  },
  {
    name: 'Classic Beef Burger', cuisine: 'Western', minutes: 30,
    image: 'recipes/classic-beef-burger.jpg', calories: 700,
    ingredients: [
      ['Ground beef', 500, 'g', 220],
      ['Burger buns', 4, 'pc', 60],
      ['Cheddar slices', 4, 'pc', 60],
      ['Lettuce', 1, 'head', 40],
      ['Tomato', 1, 'pc', 10],
      ['Onion', 1, 'pc', 15],
      ['Ketchup', 3, 'tbsp', 10],
    ],
  },
  {
    name: 'Chicken Caesar Salad', cuisine: 'Western', minutes: 25,
    image: 'recipes/chicken-caesar-salad.jpg', calories: 450,
    ingredients: [
      ['Chicken breast', 400, 'g', 130],
      ['Romaine lettuce', 2, 'head', 120],
      ['Parmesan', 50, 'g', 90],
      ['Croutons', 1, 'cup', 40],
      ['Caesar dressing', 0.5, 'cup', 80],
      ['Lemon', 1, 'pc', 20],
    ],
  },
  {
    name: 'Roast Chicken with Vegetables', cuisine: 'Western', minutes: 90,
    image: 'recipes/roast-chicken-with-vegetables.jpg', calories: 550,
    ingredients: [
      ['Whole chicken', 1.2, 'kg', 300],
      ['Potatoes', 4, 'pc', 80],
      ['Carrots', 2, 'pc', 40],
      ['Onion', 1, 'pc', 15],
      ['Garlic', 1, 'head', 15],
      ['Butter', 50, 'g', 45],
      ['Rosemary', 1, 'bunch', 40],
    ],
  },
  {
    name: 'Beef Stew', cuisine: 'Western', minutes: 150,
    image: 'recipes/beef-stew.jpg', calories: 500,
    ingredients: [
      ['Beef chuck', 1, 'kg', 480],
      ['Potatoes', 3, 'pc', 60],
      ['Carrots', 2, 'pc', 40],
      ['Celery', 2, 'stalk', 20],
      ['Onion', 1, 'pc', 15],
      ['Tomato paste', 2, 'tbsp', 15],
      ['Beef stock', 4, 'cup', 60],
      ['All-purpose flour', 2, 'tbsp', 5],
    ],
  },
  {
    name: 'Baked Mac and Cheese', cuisine: 'Western', minutes: 45,
    image: 'recipes/baked-mac-and-cheese.jpg', calories: 600,
    ingredients: [
      ['Elbow macaroni', 400, 'g', 70],
      ['Cheddar', 250, 'g', 180],
      ['Milk', 2, 'cup', 50],
      ['Butter', 50, 'g', 45],
      ['All-purpose flour', 3, 'tbsp', 6],
      ['Breadcrumbs', 0.5, 'cup', 25],
    ],
  },
  {
    name: 'Pork Chops with Mashed Potatoes', cuisine: 'Western', minutes: 40,
    image: 'recipes/pork-chops-with-mashed-potatoes.jpg', calories: 650,
    ingredients: [
      ['Pork chops', 4, 'pc', 280],
      ['Potatoes', 1, 'kg', 120],
      ['Butter', 50, 'g', 45],
      ['Milk', 0.5, 'cup', 15],
      ['Garlic', 3, 'clove', 6],
      ['Dried thyme', 1, 'tsp', 10],
    ],
  },
  {
    name: 'Fish and Chips', cuisine: 'Western', minutes: 45,
    image: 'recipes/fish-and-chips.jpg', calories: 750,
    ingredients: [
      ['Cream dory fillets', 500, 'g', 180],
      ['Potatoes', 1, 'kg', 120],
      ['All-purpose flour', 1, 'cup', 20],
      ['Sparkling water', 1, 'cup', 30],
      ['Cooking oil', 4, 'cup', 120],
      ['Lemon', 1, 'pc', 20],
      ['Tartar sauce', 0.25, 'cup', 45],
    ],
  },
  {
    name: 'Chicken Alfredo', cuisine: 'Western', minutes: 30,
    image: 'recipes/chicken-alfredo.jpg', calories: 700,
    ingredients: [
      ['Fettuccine', 500, 'g', 120],
      ['Chicken breast', 400, 'g', 130],
      ['All-purpose cream', 250, 'ml', 70],
      ['Parmesan', 80, 'g', 140],
      ['Butter', 50, 'g', 45],
      ['Garlic', 3, 'clove', 6],
    ],
  },
  {
    name: "Shepherd's Pie", cuisine: 'Western', minutes: 75,
    image: 'recipes/shepherds-pie.jpg', calories: 550,
    ingredients: [
      ['Ground beef', 500, 'g', 220],
      ['Potatoes', 1, 'kg', 120],
      ['Carrot', 1, 'pc', 20],
      ['Green peas', 100, 'g', 30],
      ['Onion', 1, 'pc', 15],
      ['Beef stock', 1, 'cup', 15],
      ['Butter', 50, 'g', 45],
      ['Tomato paste', 2, 'tbsp', 15],
    ],
  },
  {
    name: 'Tomato Soup with Grilled Cheese', cuisine: 'Western', minutes: 35,
    image: 'recipes/tomato-soup-with-grilled-cheese.jpg', calories: 500,
    ingredients: [
      ['Crushed tomatoes', 2, 'can', 140],
      ['Onion', 1, 'pc', 15],
      ['Garlic', 3, 'clove', 6],
      ['All-purpose cream', 0.5, 'cup', 35],
      ['White bread', 8, 'slice', 50],
      ['Cheddar slices', 4, 'pc', 60],
      ['Butter', 50, 'g', 45],
    ],
  },
  {
    name: 'Pan-Seared Salmon with Asparagus', cuisine: 'Western', minutes: 25,
    image: 'recipes/pan-seared-salmon-with-asparagus.jpg', calories: 450,
    ingredients: [
      ['Salmon fillets', 400, 'g', 450],
      ['Asparagus', 1, 'bunch', 180],
      ['Butter', 30, 'g', 27],
      ['Lemon', 1, 'pc', 20],
      ['Garlic', 3, 'clove', 6],
      ['Olive oil', 2, 'tbsp', 20],
    ],
  },
]

const recipes = data.map((recipe) => ({
  ...recipe,
  ingredients: recipe.ingredients.map(([name, quantity, unit, estimated_cost]) => ({
    name,
    quantity,
    unit,
    estimated_cost,
  })),
}))

export default recipes
